<!DOCTYPE html>

<html>
<head>

	<meta charset="utf-8">
	<script type="text/javascript"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script type="text/javascript" src="boostrap/js/bootstrap.js"></script>
	<script type="text/javascript" src="boostrap/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="boostrap/js/npm.js"></script>




	<link href="https://a0.muscache.com/airbnb/static/packages/common_o2.1-480b2a02b606076a457ece648a56a9b8.css" media="all" rel="stylesheet" type="text/css" />
 	<link href="https://a2.muscache.com/airbnb/static/p1/main-pretzel-4ab1c9299beb86cb6b946aef4a0c6056.css" media="screen" rel="stylesheet" type="text/css" />
 	<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
 	<link href='http://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
 	<link href='http://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
 <!-- 	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.css"> -->
<!--  	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.css.map"> -->
<!--  	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap-theme.css"> -->
<!--  	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.min.css"> -->
<!--  	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap-theme.css.map">
 	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap-theme.min.css"> -->
</head>
<style>

*  {
	/*width: 100%;*/
	border-sizing: border-box;
	-moz-box-sizing: border-box;
}

#header{
	margin-top: 50px;
	width: 100%;
	margin-left: auto;
	margin-right: auto;
}

.header-background {
	width: 100%;
	position: absolute;
	background-color: #931616;
	opacity: 0.95;
	height: 90px;
}


.logo {
	text-align: center;
	margin-top: 15px;

}

.logo h1 {
	font-family: "Satisfy", helvetica, sans-serif; 
	color: white;
	font-size: 36px;
	margin-bottom: 2px;
}

.logo p {
	font-family: "Raleway", helvetica, sans-serif; 
	color: white;
	font-weight: bold;
	font-size: 12px;
}

.logo a,
.logo a:hover {
	text-decoration: none;
}

.tab {
	margin-top:  10px;
/*	width: 50%;*/
	display: inline-block;
}

.tab li   {
	margin-top: 20px;
	margin-left: 4%;
	display: inline-block;
} 

a {
	color: white;
	font-size: 14px;
	font-family: "Raleway", helvetica, sans-serif;
	font-weight: 700;
}

a:hover {
	color: #F5F6CE;
}

.tab:first-child {
	margin-left: 10%;
}

.action-set {
	float: right;
	display: block;
/*	width: 200px;*/
	margin-bottom: 15px;
	margin-top: 15px;
}

.action-set a {
	margin-bottom: 8px;
}

.btn.btn-special{
	position: relative;
	right: 25px;
}

.search-bar {
	position: relative;
	top: -25px;
	left: 70px;
	width: 500px;
}


#search-bar #search {
	display: inline-block;
	width: 300px;
}

#search-bar #submit {{
	height: 100px;
}
</style>

<body>

	<div id="header" class="row container">
		<header>
			<div class="header-background ">

					<div class="logo col-md-3">
						<a href="main.php">
							<h1>Polis</h1>
							<p> Reprendre le pouvoir qui nous appartient</p>
						</a>	
					</div>
				<div class="nav tab list-unstyled medium-right-margin col-md-7">
					<ul class="link-reset">	
						<li><a href="main.php?theme=politique"><p>Politique</p></a></li>
						<li><a href="main.php?theme=societe"><p>Société</p></a></li>	
						<li><a href="main.php?theme=economie"><p>Economie</p></a></li>
						<li><a href="main.php?theme=technologie"><p>Technologie</p></a></li>
						<li><a href="main.php?theme=cute"><p>#Cute</p></a></li>
					</ul>
				</div>

				<div class="action-set col-md-2">

					<a class="btn btn-special" href="post.php">Rédiger un article</a>
					<br>
					<?php if(array_key_exists("ID", $_SESSION)): ?>
					<a href="logout.php">Se déconnecter</a>
					<?php else: ?>
					<a href="login.php">Se connecter</a>
					<?php endif ?>

				</div>

				<div class="search-bar col-md-6">
					<form id="search-bar" method="get" action="search.php" >
						<input id="search" type="text" placeholder="Chercher un article" name="search">
						<input id="submit" type="submit" value="Chercher">

					</form>


				</div>
			</div>
		</header>
	</div>

</body>
<script>

// 	 $("#search-bar").on("keyup", getArticle);

// 	function getArticle(){

// 		var search = $('#search').val();
// 		console.log(search);

// 		// aller chercher en ajax le résultat de la requête à la page :
// 		var config = {url: "search.php?search="+search};
		
// 		$.ajax(config).done(displayResult).fail(ajaxError);

// 	}

// // 	function displayResult(data){

// //  		$("#display").empty();
// //  		console.log(data);
// // 		for (var i = 0; i < data.search.length; i++ ){
			
// // 			$("#display").append("<tr class='result'><td>"+data[i]["title"]+"</td> <td>"+data[i]["image_url"]+"</td> <td>"+data[i]["text"]+"<td></tr>");
// // 		}	



// 	}

// 	function ajaxError () {
// 	console.log("Erreur ajax");
// }



</script>

</html>