<!DOCTYPE html>

<html>
<head>

	<meta charset="utf-8">
	<script type="text/javascript"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script type="text/javascript" src="boostrap/js/bootstrap.js"></script>
	<script type="text/javascript" src="boostrap/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="boostrap/js/npm.js"></script>




	<link href="https://a0.muscache.com/airbnb/static/packages/common_o2.1-480b2a02b606076a457ece648a56a9b8.css" media="all" rel="stylesheet" type="text/css" />
 	<link href="https://a2.muscache.com/airbnb/static/p1/main-pretzel-4ab1c9299beb86cb6b946aef4a0c6056.css" media="screen" rel="stylesheet" type="text/css" />
 <!-- 	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.css"> -->
<!--  	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.css.map"> -->
<!--  	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap-theme.css"> -->
<!--  	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap.min.css"> -->
<!--  	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap-theme.css.map">
 	<link rel="stylesheet" type="text/css" href="bootstrap/css/bootstrap-theme.min.css"> -->
</head>
<style>

body {
	background-color: #B1ABAB;

}

#login-form {
	width: 400px;
	height: 200px;
	margin: 170px auto;
	background-color: white;
	border-radius: 2%;
}

.top-border-row {
	margin-top: 15px;
	background-color: #fff !important;
	border-radius: 5%; 

}

.top-border-row h4 {
	text-align: center;
}

input {
	margin-top: 5px;
}

</style>
<body>

	<div id="login-form" class="container row">
		<div class="col-md-12">
			<div class="top-border-row col-md-12">
				<h4> Bienvenu sur votre blog</h4>

			</div>
			<div class="login-input col-md-12">
				<form method="post" action="login.php">
					<input type="text" placeholder="username" name="username">				
					<input type="password" placeholder="password" name="password">

					<input id="submit" class="btn btn-block btn-primary large btn-large padded-btn-block" type="submit" value="Connexion">
				</form>

			</div>
		</div>
	</div>




</body>


</html>