<!DOCTYPE html>

<html>
<head>

	<meta charset="utf-8">
	<script type="text/javascript"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script type="text/javascript" src="boostrap/js/bootstrap.js"></script>
	<script type="text/javascript" src="boostrap/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="boostrap/js/npm.js"></script>
	<script src="//tinymce.cachefly.net/4.1/tinymce.min.js"></script>
	<script>tinymce.init({selector:'textarea'});</script>



	<link href="https://a0.muscache.com/airbnb/static/packages/common_o2.1-480b2a02b606076a457ece648a56a9b8.css" media="all" rel="stylesheet" type="text/css" />
 	<link href="https://a2.muscache.com/airbnb/static/p1/main-pretzel-4ab1c9299beb86cb6b946aef4a0c6056.css" media="screen" rel="stylesheet" type="text/css" />
 	<link href='http://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
 </head>

<style>
body {
	background-color: #B1ABAB!important;
}

.form-container {
	width: 80%;
	height: 900px;
	margin: 0 auto !important;
	background-color: #f5f5f5;
}


#title-input {
	margin: 130px auto ;
	margin-bottom: 30px;
	width: 600px;
}



#center-form, 
#center-form input, 
#center-form p {
	margin: 20px auto;
	width: 600px;
}

#submit-article {
	width: 200px;
	margin: 50px auto;
}

</style>


<body>

<?= include("View/header.phtml");?>

	<form enctype="multipart/form-data" method="post" action="post.php">
		<div class="form-container row container">

			<input id="title-input" type="text" placeholder="Titre de l'article" name="title">

			<div id="center-form">
				<p>Rédiger votre article</p>
			<textarea id="text-input" name="text"></textarea>
			
				<p>Ajouter une image à votre article</p>
			<input id="image-input" type="file" placeholder="Ajouter une image" accept="image/*" name="image">
			</div>
			<input id="submit-article" class="btn btn-block btn-primary large btn-large padded-btn-block" type="submit" value="Publier">
		</div>

	</form>




</body>