<!DOCTYPE html>

<html>
<head>

	<meta charset="utf-8">
	<script type="text/javascript"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script type="text/javascript" src="boostrap/js/bootstrap.js"></script>
	<script type="text/javascript" src="boostrap/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="boostrap/js/npm.js"></script>




	<link href="https://a0.muscache.com/airbnb/static/packages/common_o2.1-480b2a02b606076a457ece648a56a9b8.css" media="all" rel="stylesheet" type="text/css" />
 	<link href="https://a2.muscache.com/airbnb/static/p1/main-pretzel-4ab1c9299beb86cb6b946aef4a0c6056.css" media="screen" rel="stylesheet" type="text/css" />
 	<link href='http://fonts.googleapis.com/css?family=Slabo+27px' rel='stylesheet' type='text/css'>
 </head>

 <style >
body {
	background-color: #B1ABAB!important;

}

.article-page {
	margin-top: 100px;
	margin-left: 160px!important;
	background-color: #f5f5f5;
	width: 80%;
	height: 100%;
}


#article {
	width: 72%;
	height: 100%;
	margin-right: 10px;
	
}

.article {
	margin-top: 30px;
}

.article:nth-of-type(1) {
	margin-top: 10px;
}

.article h5 {
	font-size: 30px;
	color: black;
	font-weight: 600;
	font-family: 'Slabo 27px', helvetica, arial, sans-serif;
}

.article p{
	margin-top: 20px;
	width: 550px;
	font-size: 15px;
	color: black;
	font-family: helvetica, arial, sans-serif;

}

.article img {
	margin: 5px auto;
	height: 300px;
	width: 550px;

}

.article a:hover, 
.article a {
	text-decoration: none;

}

#right-column {
	float: right;
	width: 26%;
	color: black;
	height: 100%;

}

#section-top-stories {
	margin-top: 5px;
}

.top-articles h5 {
	margin: 2px auto;
}

.top-articles a, 
.top-articles a:hover {
	color: black;
	text-decoration: none;
	font-size: 13px;
	font-weight: normal;
	font-family: 'Slabo 27px', helvetica, arial, sans-serif;
}
.top-articles hr {
	margin: 5px auto !important;

}

#section-tag a,
#section-tag li {

	color: black;
	font-family: 'Slabo 27px', helvetica, arial, sans-serif;
	  list-style-type: none;
}



/*body {
	background-color: #B1ABAB!important;

}

.article-page {
	margin: 0 auto!important;
/*	margin-left: 160px!important;*/
/*	background-color: #f5f5f5;
	width: 80%;
	
}
*/


/*#article {
	width: 100%;
	height: 100%;
	margin: 80px auto;
	background-color: #f5f5f5;
	border: solid 1px;
	
}

.article h5 {
	text-align: center;
	font-size: 30px;
	color: black;
	font-weight: 600;
	font-family: 'Slabo 27px', helvetica, arial, sans-serif;
}

.article p{
	width: 100%;
	font-size: 15px;
	color: black;
	font-family: helvetica, arial, sans-serif;

}

.article img {
    margin-left: 150px;
    margin-bottom: 20px;
	height: 300px;
	width: 550px;
}*/
 </style>

 <body>

 	<?= include("View/header.phtml");?>

 	<div class="row container article-page">
		<div id="article" class="col-md-12">
			<article>
			<?php
			echo "<div class='article'><h5>".$thisArticle["title"]."</h5><img src='".$thisArticle["image_url"]."'>"."<p>".$thisArticle["text"]."</p></a></div>";				
			?> 
			</article>
		</div>
	
			<div id="right-column" class="col-md-3">
				<div id="section-top-stories" >
					<p><strong>Derniers articles</strong></p>

							<?php

							foreach( $articles as $article){
							echo "<div class='top-articles'><a href='show.article.php?ID=".$article["ID"]."'><h5>".$article["title"]."</a><hr></div>";
							
							}
						

						?>

				</div>
				<div id="section-tag">
					<p><strong> Thèmes des articles</strong></p>
						<ul class="theme-articles">
							<li><a href="#">Politique</a></li>
							<li><a href="#">Société</a></li>
							<li><a href="#">Economie</a></li>	
							<li><a href="#">Technologie</a></li>	
							<li><a href="#">#Cute</a></li>	

						</ul>

				</div>
			</div>
	</div>




 </body>
 </html>